### ISSUE TITLE
Листинг. Ширина столбцов.

### ISSUE THREAD

**Issue by v23ent** [ZitRos/LightPivotTable#1]
Ширину столбца имеет смысл определять на основании содержимого в столбце. 
Например ширина столбца = ширина ячейки с максимальной длиной содержимого размещенного в строку. Заголовки в данном случае стоит учитывать как обычные ячейки.
При этом она меньше настройки МАХ ширины, но больше настройки MIN ширины.

**Comment by nikitaeverywhere** [comment]
@v23ent,

Как и стандартный пивот, LPT определяет ширину столбца по ширине заголовка, или по установленной в настройках ширине.

Если сделать так, как ты предлагаешь, это существенно отразиться на производительности. Любую необходимую ширину столбца можно выставить в самом пивоте.

Чтобы вносить изменение, предлагаемое тобой, нужно будет хорошо потрудится - т.к. изначально был заложен механизм расчёта "от ширины столбца". Действительно ли это так необходимо?

**Comment by v23ent** [comment]
Стандартный пивот берет MAX  от ( ширины первой ячейки столбца и ширины заголовка ). Таким образом у него получается отображение адаптируемое под данные.

Выставить ширину - вручную? Это можно сохранять per user ? или per dashboard ?

**Comment by nikitaeverywhere** [comment]
@v23ent,

Сейчас в LPT выставленные пользователем ширины не запоминаются. Ширина столбца будет равна MIN(Ширина самого заголовка, Макс. ширина). То есть, если текст не помещается - увеличьте заголовок.

Сохранение выставленной ширины заголовка можно рассматривать как отдельный запрос на добавление функциональности.

**Comment by nikitaeverywhere** [comment]
Moved to [do.intersystems.ru](Moved to do.intersystems.ru.).
