### ISSUE TITLE
Листинг. Нумерация строк.

### ISSUE THREAD

**Issue by v23ent** [ZitRos/LightPivotTable#2]
Первым столбцом стоит добавить нумерацию строк.

**Comment by nikitaeverywhere** [comment]
Можно ли реализовать это при редактировании pivot'а?

Имеется в виду измерение/показатель со счётчиком.

**Comment by v23ent** [comment]
@ZitRos 
Можно в каждый листинг дописать какое-то выражение на SQL. Но это не очень правильный подход.

**Comment by nikitaeverywhere** [comment]
Тогда запрос будет рассматриваться как опция для виджета, включение которой позволяет первым столбцом отображать номер строки. По умолчанию опция выключена.

**Comment by v23ent** [comment]
супер

**Comment by nikitaeverywhere** [comment]
Option added https://github.com/intersystems-ru/LightPivotTable/commit/6ce8a485659f0b31c450794742704075382c9346
