### ISSUE TITLE
Листинг. Выделение строк

### ISSUE THREAD

**Issue by v23ent** [ZitRos/LightPivotTable#3]
Сделать возможность множественного выделения строк. При выделении их чуть подсвечивать.
Также реализовать снятие выделения по клику на конкретную строку или снятие всего выделения.
После каждого изменения выделенных строк необходимо поддеживать в актуальном состоянии переменные дэшборда (pContext.valueList), которые передаются в качестве параметров в следующий метод класса %DeepSee.KPI: %OnDashboardAction(pAction As %String, pContext As %ZEN.proxyObject)

**Comment by nikitaeverywhere** [comment]
@v23ent,

Укажи, пожалуйста, для чего конкретно будет применяться выделение. Или это просто визуальный эффект?

**Comment by v23ent** [comment]
@ZitRos 
Выделение применяется для групповых операций, таких как например удаление. В этих случаях приложению нужно сообщить идентификаторы выделенных строк. Не HTML идентификаторы, а идентификаторы записей детальных данных.

**Comment by nikitaeverywhere** [comment]
@v23ent,

В таком случае, стоит это рассматривать как добавление функциональности, а именно - возможность удалять выделенные данные, а более обобщённо - возможность редактировать данные напрямую из LPT. Правильно?

**Comment by v23ent** [comment]
@ZitRos 
Не правильно.
Удаление может быть комплексной процедурой. А также другие действия могут быть какими угодно. LPT это беспокоить не должно. LPT отобразил, у него там что-то выделили, он сообщил что у него выделено.

**Comment by nikitaeverywhere** [comment]
Хорошо, в таком случае цель - исключительно сообщить DeepSee о выделенной области?

**Comment by nikitaeverywhere** [comment]
Просьба составить пример того, как это работает со стандартном пивотом на 37.139.4.54.

**Comment by nikitaeverywhere** [comment]
Moved to [do.intersystems.ru](Moved to do.intersystems.ru.).
