### ISSUE TITLE
Общее. Применение фильтров URL

### ISSUE THREAD

**Issue by v23ent** [ZitRos/LightPivotTable#4]
Проблема связана с вызовом Дэшборда, когда в URL передаются фильтры в виде: 
SETTINGS=FILTER:...~...~%5Bstatus%5D.%5BH1%5D.%5Bstatus%5D.%26%5BОжидает%20на%20текущую%20дату%5D;

Стандартный виджет (наверное виджет, возможно дэшборд) разбирает этот URL и применяет эти фильтры к содержащемуся внутри пивоту. В случае если измерение пришедшее в URL содержится в списке контролов виджета, то это значение фильтра еще и отображается, а если не сожержится - просто применяется.
Виджет с LPT производит разбор фильтров из URL и даже подставляет их значения в контролы, если соответствующие вынесены на виджет. Но применения этих фильтров не происходит.

**Comment by nikitaeverywhere** [comment]
Просьба создать проблемный пивот (дешборд) на 37.139.4.54 для демонстрации проблемы.

**Comment by nikitaeverywhere** [comment]
Moved to [do.intersystems.ru](Moved to do.intersystems.ru.).
