### ISSUE TITLE
Листинг. ID ячеек

### ISSUE THREAD

**Issue by v23ent** [ZitRos/LightPivotTable#5]
Было бы здорово всем ячейкам проставить id вида cell_1_2 например.

**Comment by nikitaeverywhere** [comment]
@v23ent,

Для чего данный идентификатор будет применяться? Где будет отображён, и какова его роль в таблице?

**Comment by v23ent** [comment]
@ZitRos 
![2015-05-26 15 27 47](https://cloud.githubusercontent.com/assets/12609489/7812537/ceda449e-03bb-11e5-8710-85f8403727bf.png)

Для удобства навигации.

**Comment by nikitaeverywhere** [comment]
@v23ent,

Выглядит совсем не здорово, так как стандарты HTML запрещают использование двух или более одинаковых идентификаторов на странице. А виджетов на странице с LPT может быть много.

К тому же, даже если называть ячейки вида id="uniqueTableName-cell-1-3", удобства для внутренних механизмов LPT здесь не наблюдаю - возможно, имеется в виду взаимодействие с другими модулями? Какая конечная цель данного приёма?

**Comment by v23ent** [comment]
@ZitRos 
Это для применения функциональности "поверх" LPT. Для простоты применения каких-либо действий с рядом или столбцом.

**Comment by nikitaeverywhere** [comment]
> Это для применения функциональности "поверх" LPT.

Было бы интересно узнать, что за функциональность "поверх" вы хотите реализовать. В таком случае правильно расширять API LPT, а не модифицировать HTML код, который он генерирует.

Для примера, у вас не получится занести ячейку в переменную, используя getElementById(...) - однажды она потеряется, так как пивот для каждой новой страницы (отображение, поиск, сортировка) генерирует новые элементы.

**Comment by nikitaeverywhere** [comment]
Вопрос обговорен, принято решение использовать стандартные методы - поиск элементов в дереве HTML по индексам.
