### ISSUE TITLE
Trigger на событие завершения создания таблицы в DOM

### ISSUE THREAD

**Issue by v23ent** [ZitRos/LightPivotTable#6]
Просьба добавить триггер на событие "lpt отрисовался". Причем "отрисовался" после любой загрузки: первичная загрузка, обновление, drillThrough, переход на другую страницу.

**Comment by nikitaeverywhere** [comment]
Added https://github.com/intersystems-ru/LightPivotTable/commit/09a6a373a7c014e20e575bec9c9841e4b119f7df
